# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    app.public_images_directory: 'uploads/images'
    app.project_images_directory: '%kernel.project_dir%/public/%app.public_images_directory%'
    app.censurator_file: '%kernel.project_dir%/data/words_censurator.txt'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Util\Uploader:
        arguments:
            $directory: '%app.project_images_directory%'

    App\Util\Censurator:
        arguments:
            $fichier: '%app.censurator_file%'
